import torch
import matplotlib.pyplot as plt
from scipy import signal

# k = 32
# window = signal.windows.triang(k)
# avg = lambda sig: signal.convolve(sig, window, mode='valid')
# fs=32
# lw=4
# fig, ax = plt.subplots(ncols=1, nrows=5, figsize=(24, 24))
# ax[0].plot(avg(history_1['train_loss']), label='train_1',  lw=lw, c='C0')
# ax[0].plot(avg(history_1['val_loss']), label='val_1', ls='--', lw=lw, c='C0')
# ax[1].plot(avg(history_2['train_loss']), label='train_2',  lw=lw, c='C1')
# ax[1].plot(avg(history_2['val_loss']), label='val_2', ls='--', lw=lw, c='C1')
# ax[2].plot(avg(history_3['train_loss']), label='train_3',  lw=lw, c='C2')
# ax[2].plot(avg(history_3['val_loss']), label='val_3', ls='--', lw=lw, c='C2')
# ax[3].plot(avg(history_4['train_loss']), label='train_4',  lw=lw, c='C3')
# ax[3].plot(avg(history_4['val_loss']), label='val_4', ls='--', lw=lw, c='C3')
# ax[4].plot(avg(history_5['train_loss']), label='train_5',  lw=lw, c='C3')
# ax[4].plot(avg(history_5['val_loss']), label='val_5', ls='--', lw=lw, c='C3')
# ax[0].tick_params(axis='both', which='major', labelsize=fs, pad=15)
# ax[1].tick_params(axis='both', which='major', labelsize=fs, pad=15)
# ax[2].tick_params(axis='both', which='major', labelsize=fs, pad=15)
# ax[3].tick_params(axis='both', which='major', labelsize=fs, pad=15)
# ax[4].tick_params(axis='both', which='major', labelsize=fs, pad=15)
# ax[0].set_title('single model 1')
# ax[1].set_title('single model 2')
# ax[2].set_title('single model 3')
# ax[3].set_title('multi model 1')
# ax[4].set_title('multi model 2')
# # ax[0,0].set_ylim(0.23, 0.27)
# ax[0].set_xlabel('epochs', fontsize=fs)
# ax[1].set_xlabel('epochs', fontsize=fs)
# ax[2].set_xlabel('epochs', fontsize=fs)
# ax[3].set_xlabel('epochs', fontsize=fs)
# ax[4].set_xlabel('epochs', fontsize=fs)
# ax[0].set_ylabel('loss', fontsize=fs)
# ax[1].set_ylabel('loss', fontsize=fs)
# ax[3].set_ylabel('loss', fontsize=fs)
# ax[4].set_ylabel('loss', fontsize=fs)
# ax[5].set_ylabel('loss', fontsize=fs)
# plt.tight_layout(w_pad=4)
# # plt.legend(fontsize=fs, ncol=3, bbox_to_anchor=(0.60, -0.30))
# # plt.savefig('figures/midslice-loss.svg')
# plt.show()